<?php

use App\Exports\RequestorGlobalExport;
use App\Http\Livewire\Faq;
use App\Http\Livewire\Blog;
use App\Http\Livewire\Chat;
use App\Http\Livewire\Flex;
use App\Http\Livewire\Tabs;
use App\Http\Livewire\Tags;
use App\Http\Livewire\Badge;
use App\Http\Livewire\Cards;
use App\Http\Livewire\Icons;
use App\Http\Livewire\Index;
use App\Http\Livewire\Reset;
use App\Http\Livewire\Toast;
use App\Http\Livewire\Width;
use Maatwebsite\Excel\Facades\Excel;
use App\Http\Livewire\Alerts;
use App\Http\Livewire\Avatar;
use App\Http\Livewire\Border;
use App\Http\Livewire\Extras;
use App\Http\Livewire\Forgot;
use App\Http\Livewire\Height;
use App\Http\Livewire\Icons2;
use App\Http\Livewire\Icons3;
use App\Http\Livewire\Icons4;
use App\Http\Livewire\Icons5;
use App\Http\Livewire\Icons6;
use App\Http\Livewire\Images;
use App\Http\Livewire\Margin;
use App\Http\Livewire\Modals;
use App\Http\Livewire\Rating;
use App\Http\Livewire\Search;
use App\Http\Livewire\Signin;
use App\Http\Livewire\Signup;
use App\Http\Livewire\Buttons;
use App\Http\Livewire\Display;
use App\Http\Livewire\Gallery;
use App\Http\Livewire\Invoice;
use App\Http\Livewire\Padding;
use App\Http\Livewire\Popover;
use App\Http\Livewire\Pricing;
use App\Http\Livewire\Profile;
use App\Http\Livewire\Tooltip;
use App\Http\Livewire\Widgets;
use App\Http\Livewire\Calendar;
use App\Http\Livewire\Carousel;
use App\Http\Livewire\Collapse;
use App\Http\Livewire\Contacts;
use App\Http\Livewire\Counters;
use App\Http\Livewire\Dropdown;
use App\Http\Livewire\Error404;
use App\Http\Livewire\Error500;
use App\Http\Livewire\MailRead;
use App\Http\Livewire\Position;
use App\Http\Livewire\Products;
use App\Http\Livewire\Progress;
use App\Http\Livewire\Spinners;
use App\Http\Livewire\Timeline;
use App\Http\Livewire\Todotask;
use App\Http\Livewire\Treeview;
use App\Http\Livewire\Userlist;
use App\Http\Livewire\Vertical;
use App\Http\Livewire\Accordion;
use App\Http\Livewire\ChartFlot;
use App\Http\Livewire\Emptypage;
use App\Http\Livewire\ListGroup;
use App\Http\Livewire\MailInbox;
use App\Http\Livewire\MapVector;
use App\Http\Livewire\TableData;
use App\Http\Livewire\Background;
use App\Http\Livewire\Bloglist01;
use App\Http\Livewire\Bloglist02;
use App\Http\Livewire\Bloglist03;
use App\Http\Livewire\Bloglist04;
use App\Http\Livewire\Bloglist05;
use App\Http\Livewire\ChartPeity;
use App\Http\Livewire\FormEditor;
use App\Http\Livewire\FormUpload;
use App\Http\Livewire\Horizontal;
use App\Http\Livewire\Lockscreen;
use App\Http\Livewire\MapLeaflet;
use App\Http\Livewire\Navigation;
use App\Http\Livewire\Pagination;
use App\Http\Livewire\SweetAlert;
use App\Http\Livewire\TableBasic;
use App\Http\Livewire\Thumbnails;
use App\Http\Livewire\Typography;
use App\Http\Livewire\Breadcrumbs;
use App\Http\Livewire\ChartEchart;
use App\Http\Livewire\ChartMorris;
use App\Http\Livewire\Editprofile;
use App\Http\Livewire\FormLayouts;
use App\Http\Livewire\FormWizards;
use App\Http\Livewire\MailCompose;
use App\Http\Livewire\MediaObject;
use App\Http\Livewire\ProductCart;
use App\Http\Livewire\Rangeslider;
use App\Http\Livewire\ChartChartjs;
use App\Http\Livewire\FormAdvanced;
use App\Http\Livewire\FormElements;
use App\Http\Livewire\ImageCompare;
use App\Http\Livewire\MailSettings;
use App\Http\Livewire\Notification;
use App\Http\Livewire\FormInputmask;
use Illuminate\Support\Facades\Auth;
use App\Http\Livewire\ChartSparkline;
use App\Http\Livewire\Darggablecards;
use App\Http\Livewire\FormValidation;
use App\Http\Livewire\ProductDetails;
use Illuminate\Support\Facades\Route;
use App\Http\Livewire\ProductCheckout;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\UserController;
use App\Http\Livewire\FormElementsSizes;
use App\Http\Livewire\Underconstruction;
use App\Http\Livewire\WidgetNotification;
use App\Exports\VCustomerMonitoringExport;
use App\Http\Controllers\AdjustmentController;
use App\Http\Controllers\ApplicantController;
use App\Http\Controllers\ApplicantGlobalController;
use App\Http\Controllers\ApprovalController;
use App\Http\Controllers\BranchlistController;
use App\Http\Controllers\ProgressBarController;
use App\Http\Controllers\Auth\LoginehrController;
use App\Http\Controllers\CompanyRateController;
use App\Http\Controllers\CreditFormController;
use App\Http\Controllers\DataAdjustmentController;
use App\Http\Controllers\DataApprovalController;
use App\Http\Controllers\DataDisbursementController;
use App\Http\Controllers\DataExpiredController;
use App\Http\Controllers\DataExpiredNasabahController;
use App\Http\Controllers\DataRejectionController;
use App\Http\Controllers\RawDataController;
use App\Http\Controllers\DataScoringController;
use App\Http\Controllers\DBRController;
use App\Http\Controllers\DBRUsahaController;
use App\Http\Controllers\DisbursementController;
use App\Http\Controllers\DownloadAdjustmentController;
use App\Http\Controllers\DownloadApprovalController;
use App\Http\Controllers\DownloadDisbursementController;
use App\Http\Controllers\DownloadPemohonController;
use App\Http\Controllers\DownloadPermohonanController;
use App\Http\Controllers\DownloadRejectionController;
use App\Http\Controllers\DownloadRequestorController;
use App\Http\Controllers\ExportGlobalApplicationController;
use App\Http\Controllers\ExportGlobalSimulasiController;
use App\Http\Controllers\ExportTodayApplicationController;
use App\Http\Controllers\ExportTodaySimulasiController;
use App\Http\Controllers\IndustryController;
use App\Http\Controllers\NasabahGlobalController;
use App\Http\Controllers\ProxyController;
use App\Http\Controllers\RequestorGlobalController;
use App\Http\Controllers\ScoringController;
use App\Http\Controllers\SimulasiController;
use App\Http\Controllers\SimulasiGlobalController;
use App\Http\Controllers\TesDataRequestController;
use App\Http\Controllers\TodayApprovalController;
use App\Http\Controllers\TodayRejectionController;
use App\Http\Controllers\VCustomerMonitoringController;
use App\Models\KTAAdjustmentModel;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::post('loginehr', [LoginehrController::class, 'login'])->name('loginehr');
Route::post('logouts', [LoginehrController::class, 'logouts'])->name('logouts');

// Route::get('/', function () {
//     return view('livewire.index');
// });
Route::get('/', [HomeController::class, 'index']);
Route::post('/proxy', [ProxyController::class, 'forwardRequest'])->name('forwardRequest');
Route::any('/test', function (Request $request) {
    Log::info('Method: ' . $request->method());
    return response()->json(['method' => $request->method()]);
});
Route::resource('users', UserController::class);
Route::resource('perusahaan', CompanyRateController::class);
Route::resource('industri', IndustryController::class);
Route::get('branch-search', [UserController::class, 'branchSearch']);
Route::get('role-search', [UserController::class, 'roleSearch']);
Route::resource('branch', BranchlistController::class);
Route::get('status-search', [UserController::class, 'statusSearch']);
Route::get('nik-search', [UserController::class, 'nikSearch']);
Route::get('get-nik/{id}', [UserController::class, 'getFromNIK']);
Route::get('get-datanik/{id}', [UserController::class, 'getDataNIK']);
Route::resource('branch', BranchlistController::class);
Route::resource('simulasi-today', SimulasiController::class);
Route::resource('simulasi-global', SimulasiGlobalController::class);
Route::resource('application-today', ApplicantController::class);
Route::resource('application-global', ApplicantGlobalController::class);
Route::resource('requestor', RequestorGlobalController::class);
Route::resource('nasabah', NasabahGlobalController::class);
Route::resource('datascoring', ScoringController::class);
Route::resource('adjustment', AdjustmentController::class);
Route::resource('dataadjustment', DataAdjustmentController::class);
Route::resource('dbr', DBRController::class);
Route::resource('dbrusaha', DBRUsahaController::class);
Route::resource('doscoring', DataScoringController::class);
Route::resource('approval', ApprovalController::class);
Route::resource('dataapproval', DataApprovalController::class);
Route::resource('negativeactivity', DataRejectionController::class);
Route::resource('rawdata', RawDataController::class);
Route::resource('eform', TesDataRequestController::class);
Route::get('validateRek/{id}', [TesDataRequestController::class, 'validateRekening']);
Route::get('validateNIK/{id}', [TesDataRequestController::class, 'validateNIK']);
Route::resource('dataexpired', DataExpiredController::class);
Route::resource('dataexpirednasabah', DataExpiredNasabahController::class);
Route::resource('todayapproval', TodayApprovalController::class);
Route::resource('todayrejection', TodayRejectionController::class);
Route::resource('disbursement', DisbursementController::class);
Route::resource('datadisbursement', DataDisbursementController::class);
Route::resource('creditform', CreditFormController::class);
Route::post('getpdf', [CreditFormController::class, 'toPDF'])->name('getpdf');
Route::get('/tocheck',[CreditFormController::class, 'toCheck']);
Route::get('approve/{ref_no}', [ApprovalController::class, 'approve'])->name('approve');
Route::get('reject/{ref_no}', [ApprovalController::class, 'reject'])->name('reject');
Route::get('zipDownload/{nik}', [NasabahGlobalController::class, 'zipDownload'])->name('zipDownload');
Route::get('simtoday/exportexcel', [ExportTodaySimulasiController::class, 'exportexcel']);
Route::get('simtoday/exportcsv', [ExportTodaySimulasiController::class, 'exportcsv']);
Route::get('appstoday/exportexcel', [ExportTodayApplicationController::class, 'exportexcel']);
Route::get('appstoday/exportcsv', [ExportTodayApplicationController::class, 'exportcsv']);
Route::post('storeacc', [DBRController::class, 'storeacc'])->name('storeacc');
Route::post('updateacc/{ref_no}', [DBRController::class, 'updateacc'])->name('updateacc');
Route::post('storeaccusaha', [DBRUsahaController::class, 'storeaccusaha'])->name('storeaccusaha');
Route::post('updateaccusaha/{ref_no}', [DBRUsahaController::class, 'updateaccusaha'])->name('updateaccusaha');
Route::delete('hapusdbrusaha/{id}', [DBRUsahaController::class, 'hapusdbrusaha'])->name('hapusdbrusaha');
Route::delete('hapusdbr/{id}', [DBRController::class, 'hapusdbr'])->name('hapusdbr');
Route::delete('deletescoring/{ref_no}', [DataScoringController::class, 'deletescoring'])->name('deletescoring');
Route::resource('exportsimulasi', ExportGlobalSimulasiController::class);
Route::resource('exportapplication', ExportGlobalApplicationController::class);
Route::resource('downloadrequestor', DownloadRequestorController::class);
Route::resource('downloadpemohon', DownloadPemohonController::class);
Route::resource('downloadapproval', DownloadApprovalController::class);
Route::resource('downloadrejection', DownloadRejectionController::class);
Route::resource('downloadpermohonan', DownloadPermohonanController::class);
Route::resource('downloadadjustment', DownloadAdjustmentController::class);
Route::resource('downloaddisbursement', DownloadDisbursementController::class);

Route::get('index', Index::class);
Route::get('accordion', Accordion::class);
Route::get('alerts', Alerts::class);
Route::get('avatar', Avatar::class);
Route::get('background', Background::class);
Route::get('badge', Badge::class);
Route::get('blog', Blog::class);
Route::get('bloglist01', Bloglist01::class);
Route::get('bloglist02', Bloglist02::class);
Route::get('bloglist03', Bloglist03::class);
Route::get('bloglist04', Bloglist04::class);
Route::get('bloglist05', Bloglist05::class);
Route::get('border', Border::class);
Route::get('breadcrumbs', Breadcrumbs::class);
Route::get('buttons', Buttons::class);
Route::get('calendar', Calendar::class);
Route::get('cards', Cards::class);
Route::get('carousel', Carousel::class);
Route::get('chart-chartjs', ChartChartjs::class);
Route::get('chart-echart', ChartEchart::class);
Route::get('chart-flot', ChartFlot::class);
Route::get('chart-morris', ChartMorris::class);
Route::get('chart-peity', ChartPeity::class);
Route::get('chart-sparkline', ChartSparkline::class);
Route::get('chat', Chat::class);
Route::get('collapse', Collapse::class);
Route::get('contacts', Contacts::class);
Route::get('counters', Counters::class);
Route::get('darggablecards', Darggablecards::class);
Route::get('display', Display::class);
Route::get('dropdown', Dropdown::class);
Route::get('editprofile', Editprofile::class);
Route::get('emptypage', Emptypage::class);
Route::get('error404', Error404::class);
Route::get('error500', Error500::class);
Route::get('extras', Extras::class);
Route::get('faq', Faq::class);
Route::get('flex', Flex::class);
Route::get('forgot', Forgot::class);
Route::get('form-advanced', FormAdvanced::class);
Route::get('form-editor', FormEditor::class);
Route::get('form-elements', FormElements::class);
Route::get('form-elements-sizes', FormElementsSizes::class);
Route::get('form-inputmask', FormInputmask::class);
Route::get('form-layouts', FormLayouts::class);
Route::get('form-upload', FormUpload::class);
Route::get('form-validation', FormValidation::class);
Route::get('form-wizards', FormWizards::class);
Route::get('gallery', Gallery::class);
Route::get('height', Height::class);
Route::get('horizontal', Horizontal::class);
Route::get('icons', Icons::class);
Route::get('icons2', Icons2::class);
Route::get('icons3', Icons3::class);
Route::get('icons4', Icons4::class);
Route::get('icons5', Icons5::class);
Route::get('icons6', Icons6::class);
Route::get('image-compare', ImageCompare::class);
Route::get('images', Images::class);
Route::get('invoice', Invoice::class);
Route::get('list-group', ListGroup::class);
Route::get('lockscreen', Lockscreen::class);
Route::get('mail-compose', MailCompose::class);
Route::get('mail-inbox', MailInbox::class);
Route::get('mail-read', MailRead::class);
Route::get('mail-settings', MailSettings::class);
Route::get('map-leaflet', MapLeaflet::class);
Route::get('map-vector', MapVector::class);
Route::get('margin', Margin::class);
Route::get('media-object', MediaObject::class);
Route::get('modals', Modals::class);
Route::get('navigation', Navigation::class);
Route::get('notification', Notification::class);
Route::get('padding', Padding::class);
Route::get('pagination', Pagination::class);
Route::get('popover', Popover::class);
Route::get('position', Position::class);
Route::get('pricing', Pricing::class);
Route::get('product-cart', ProductCart::class);
Route::get('product-checkout', ProductCheckout::class);
Route::get('product-details', ProductDetails::class);
Route::get('products', Products::class);
Route::get('profile', Profile::class);
Route::get('progress', Progress::class);
Route::get('rangeslider', Rangeslider::class);
Route::get('rating', Rating::class);
Route::get('reset', Reset::class);
Route::get('search', Search::class);
Route::get('signin', Signin::class);
Route::get('signup', Signup::class);
Route::get('spinners', Spinners::class);
Route::get('sweet-alert', SweetAlert::class);
Route::get('table-basic', TableBasic::class);
Route::get('table-data', TableData::class);
Route::get('tabs', Tabs::class);
Route::get('tags', Tags::class);
Route::get('thumbnails', Thumbnails::class);
Route::get('timeline', Timeline::class);
Route::get('toast', Toast::class);
Route::get('todotask', Todotask::class);
Route::get('tooltip', Tooltip::class);
Route::get('treeview', Treeview::class);
Route::get('typography', Typography::class);
Route::get('underconstruction', Underconstruction::class);
Route::get('userlist', Userlist::class);
Route::get('vertical', Vertical::class);
Route::get('widget-notification', WidgetNotification::class);
Route::get('widgets', Widgets::class);
Route::get('width', Width::class);
